/**
 * useSession — React Context for session management
 *
 * Manages the X-Session-ID header lifecycle across all API calls.
 * The session ID is generated by the backend on first model upload
 * and must be sent in all subsequent requests.
 */

import { createContext, useContext, useState, useRef } from "react";
import axios from "axios";

const SessionContext = createContext(null);

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:8000/api";

// Axios instance with session header injection
export const createApiClient = (sessionId) => {
  const client = axios.create({
    baseURL: API_BASE,
    timeout: 300000, // 2 min timeout for SHAP computation
    headers: {
      "Content-Type": "application/json",
      ...(sessionId ? { "X-Session-ID": sessionId } : {}),
    },
  });

  // Response interceptor: capture session ID from server response
  client.interceptors.response.use(
    (response) => {
      const sid = response.headers["x-session-id"];
      if (sid) response._sessionId = sid;
      return response;
    },
    (error) => {
      const message =
        error.response?.data?.detail ||
        error.response?.data?.message ||
        error.message ||
        "Unknown error";
      return Promise.reject(new Error(message));
    }
  );

  return client;
};

export function SessionProvider({ children }) {
  const [sessionId, setSessionId] = useState(null);
  const [modelInfo, setModelInfo] = useState(null);
  const [dataInfo, setDataInfo] = useState(null);
  const [isReady, setIsReady] = useState(false);

  const apiClient = useRef(createApiClient(null));

  const updateSession = (id) => {
    setSessionId(id);
    apiClient.current = createApiClient(id);
  };

  const uploadModel = async (file) => {
    const formData = new FormData();
    formData.append("file", file);

    const response = await apiClient.current.post("/upload-model", formData, {
      headers: { "Content-Type": "multipart/form-data" },
    });

    const sid = response.headers["x-session-id"] || response.data.session_id;
    if (sid) updateSession(sid);
    setModelInfo(response.data);
    return response.data;
  };

  const uploadData = async (file, targetColumn = "") => {
    const formData = new FormData();
    formData.append("file", file);
    if (targetColumn) formData.append("target_column", targetColumn);

    const response = await apiClient.current.post("/upload-data", formData, {
      headers: { "Content-Type": "multipart/form-data" },
    });

    setDataInfo(response.data);
    if (modelInfo && dataInfo) setIsReady(true);
    return response.data;
  };

  const generateExplanations = async (params = {}) => {
    const response = await apiClient.current.post("/generate-explanations", {
      instance_index: params.instanceIndex || 0,
      num_lime_features: params.numLimeFeatures || 10,
      num_lime_samples: params.numLimeSamples || 5000,
      background_sample_size: params.backgroundSamples || 100,
    });
    return response.data;
  };

  const fetchMetrics = async () => {
    const response = await apiClient.current.get("/metrics");
    return response.data;
  };

  return (
    <SessionContext.Provider
      value={{
        sessionId,
        modelInfo,
        dataInfo,
        isReady,
        uploadModel,
        uploadData,
        generateExplanations,
        fetchMetrics,
        setIsReady,
      }}
    >
      {children}
    </SessionContext.Provider>
  );
}

export function useSession() {
  const ctx = useContext(SessionContext);
  if (!ctx) throw new Error("useSession must be used within SessionProvider");
  return ctx;
}
